name: Test Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.5.0'
      - name: Install npm packages
        run: npm ci
      - name: Build
        run: npm run production
      - name: clean git pages cache
        run: rm -rf node_modules/gh-pages/.cache
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
        env:
          PUBLISH_DIR: _site 
          PUBLISH_BRANCH: gh-pages
